Repository player-ui/rules_player, pull requests merged in 2022-08, with the labels that each got.

#13 Add publish and stamping support to VSCE rule
  player/README.md
  player/vsce/BUILD
  player/vsce/index.bzl
  player/vsce/package.bzl
  player/vsce/vsce_stamp.bzl
  player/vsce/vsce_stamp.js
Labels: minor

#15 Add build badge to README
  README.md
Labels: documentation, skip-release

#16 Fix non-utf8 files from being changed during nextjs stamping
  javascript/next/next.build.js
  player/vsce/vsce_stamp.js
Labels: patch

#19 Update gh_pages and enable tarball stamping
  distribution/index.bzl
  distribution/tar/BUILD
  distribution/tar/stamp_tar_files.bzl
  distribution/tar/stamp_tar_files.js
  gh-pages/gh-pages.js
Labels: minor

#20 update swift rules to work with xcode 13.3+
  apple/workspace.bzl
Labels: minor
