Repository player-ui/rules_player, pull requests merged in 2024-07, with the labels that each got.

#43 Oclif Macro
  javascript/defs.bzl
  javascript/private/oclif.bzl
Labels: patch

#45 Bazel 6 xlr
  javascript/private/js_pipeline.bzl
  player/defs.bzl
  player/private/BUILD
  player/private/dsl.bzl
  player/private/js_xlr_pipeline.bzl
  player/private/xlr.bzl
Labels: patch

#44 Update config search path to remove bin/ prefix
  javascript/private/js_pipeline.bzl
  player/defs.bzl
  player/private/BUILD
  player/private/config.bzl
  player/private/dsl.bzl
  player/private/js_xlr_pipeline.bzl
  player/private/player.config.js.template
  player/private/player.config.json.template
  player/private/xlr.bzl
Labels: patch, Bazel 6

#50 Bazel 6 JVM
  .bazelignore
  MODULE.bazel
  WORKSPACE
  WORKSPACE.bzlmod
  conf.bzl
  distribution/BUILD
  index.bzl
  kotlin/BUILD
  kotlin/defs.bzl
  kotlin/example/.bazelrc
  kotlin/example/.bazelversion
  kotlin/example/BUILD
  kotlin/example/MODULE.bazel
  kotlin/example/WORKSPACE
  kotlin/example/lib.kt
  kotlin/example/libtest.kt
  kotlin/private/BUILD
  kotlin/private/distribution.bzl
  kotlin/private/junit5.bzl
  kotlin/private/junit_test.bzl
  kotlin/private/kt_jvm.bzl
  kotlin/private/kt_jvm_library_and_test.bzl
  kotlin/private/lint.bzl
  kotlin/private/scope_name.bzl
  player/private/dsl.bzl
Labels: patch

#53 Update docs
  .circleci/config.yml
  docs/rules.md
  javascript/BUILD
  javascript/private/BUILD
Labels: Bazel 6

#57 Update Generated Release Notes to Conform to Bazel 6 Standard
  scripts/bazel-usage-note-auto-plugin.js
Labels: skip-release

#51 iOS publishing rule updates
  ios/defs.bzl
  ios/private/BUILD
  ios/private/pod_repo_push.sh
  ios/private/pod_trunk_push.sh
  ios/private/publishing.bzl
  ios/private/push.sh
  ios/private/unzip_and_tag.sh
Labels: patch

#58 Generate docs for all rules
  MODULE.bazel
  docs/BUILD
  docs/ios.md
  docs/javascript.md
  docs/kotlin.md
  docs/player.md
  ios/private/BUILD
  kotlin/private/BUILD
  kotlin/private/kt_jvm.bzl
  player/BUILD
  player/private/BUILD
  player/private/dsl.bzl
  player/private/js_xlr_pipeline.bzl
Labels: documentation, internal

#59 Update examples to use rules_bazel_integration_test
  .bazelignore
  .bazelrc
  .circleci/config.yml
  BUILD
  MODULE.bazel
  examples/BUILD
  examples/kotlin/.bazelrc
  examples/kotlin/.bazelversion
  examples/kotlin/BUILD
  examples/kotlin/MODULE.bazel
  examples/kotlin/WORKSPACE
  examples/kotlin/lib.kt
  examples/kotlin/libtest.kt
  examples/ts-monorepo/.bazelignore
  examples/ts-monorepo/.bazelrc
  examples/ts-monorepo/.bazelversion
  examples/ts-monorepo/.eslintrc.js
  examples/ts-monorepo/BUILD
  examples/ts-monorepo/MODULE.bazel
  examples/ts-monorepo/VERSION
  examples/ts-monorepo/WORKSPACE
  examples/ts-monorepo/package.json
  examples/ts-monorepo/packages/module-a/BUILD
  examples/ts-monorepo/packages/module-a/README.md
  examples/ts-monorepo/packages/module-a/package.json
  examples/ts-monorepo/packages/module-a/src/index.test.ts
  examples/ts-monorepo/packages/module-a/src/index.ts
  examples/ts-monorepo/packages/module-a/tsup.config.ts
  examples/ts-monorepo/packages/module-a/vitest.config.ts
  examples/ts-monorepo/packages/module-b/BUILD
  examples/ts-monorepo/packages/module-b/package.json
  examples/ts-monorepo/packages/module-b/package.test.json
  examples/ts-monorepo/packages/module-b/src/__tests__/entry.test.ts
  examples/ts-monorepo/packages/module-b/src/cli.ts
  examples/ts-monorepo/packages/module-b/src/entry.ts
  examples/ts-monorepo/packages/module-b/src/index.ts
  examples/ts-monorepo/packages/module-b/tsup.config.ts
  examples/ts-monorepo/packages/module-b/vitest.config.ts
  examples/ts-monorepo/pnpm-lock.yaml
  examples/ts-monorepo/pnpm-workspace.yaml
  examples/ts-monorepo/tsconfig.json
  examples/ts-monorepo/tsup.config.ts
  examples/ts-monorepo/vitest.config.ts
  examples/ts-monorepo/workspace_status.sh
  javascript/BUILD
  javascript/private/BUILD
  kotlin/BUILD
  kotlin/private/BUILD
  scripts/test.sh
Labels: skip-release, internal

#60 Lint & Fix all *.bzl files
  BUILD
  MODULE.bazel
  WORKSPACE
  distribution/BUILD
  docs/BUILD
  docs/ios.md
  docs/javascript.md
  docs/kotlin.md
  docs/player.md
  examples/kotlin/BUILD
  examples/kotlin/MODULE.bazel
  examples/kotlin/WORKSPACE
  examples/ts-monorepo/BUILD
  examples/ts-monorepo/MODULE.bazel
  examples/ts-monorepo/WORKSPACE
  examples/ts-monorepo/packages/module-b/BUILD
  internal/BUILD
  internal/private/BUILD
  internal/private/stamp.bzl
  ios/BUILD
  ios/defs.bzl
  ios/private/BUILD
  ios/private/common_utils.bzl
  ios/private/publishing.bzl
  javascript/BUILD
  javascript/defs.bzl
  javascript/private/BUILD
  javascript/private/eslint.bzl
  javascript/private/js_pipeline.bzl
  javascript/private/oclif.bzl
  javascript/private/package_json.bzl
  javascript/private/tsup.bzl
  javascript/private/utils.bzl
  javascript/private/vitest.bzl
  kotlin/BUILD
  kotlin/defs.bzl
  kotlin/distribution.bzl
  kotlin/private/BUILD
  kotlin/private/distribution.bzl
  kotlin/private/junit5.bzl
  kotlin/private/junit_test.bzl
  kotlin/private/kt_jvm.bzl
  kotlin/private/kt_jvm_library_and_test.bzl
  kotlin/private/lint.bzl
  kotlin/private/scope_name.bzl
  player/BUILD
  player/defs.bzl
  player/private/BUILD
  player/private/dsl.bzl
  player/private/js_xlr_pipeline.bzl
  player/private/xlr.bzl
Labels: documentation, internal
