Repository player-ui/rules_player, pull requests merged in 2024-08, with the labels that each got.

#62 Bazel6 - stamping tars, generating gh-page.js, and deploying gh-pages
  .circleci/config.yml
  MODULE.bazel
  distribution/tar/BUILD
  distribution/tar/defs.bzl
  distribution/tar/private/BUILD
  distribution/tar/private/stamp_tar_files.bzl
  distribution/tar/private/stamp_tar_files.mjs
  gh-pages/BUILD
  gh-pages/defs.bzl
  gh-pages/private/BUILD
  gh-pages/private/gh-deploy.bzl
  gh-pages/private/gh-pages.ts
  package.json
  pnpm-lock.yaml
  tsup.config.ts
  yarn.lock
Labels: minor

#64 Gitignore - ghpage.js update
  .gitignore
Labels: patch

#65 Gitignore update
  .gitignore
Labels: patch

#67 Add GH script
  gh-pages/private/gh-pages.js
Labels: patch

#69 Removing generation of js file
  .circleci/config.yml
Labels: patch

#70 Fix stamp_tar_files
  distribution/tar/private/stamp_tar_files.bzl
  distribution/tar/private/stamp_tar_files.mjs
  gh-pages/private/gh-pages.js
Labels: patch

#71 Stamping Fix - Calls the right stamp file
  distribution/tar/private/stamp_tar_files.bzl
  distribution/tar/private/stamp_tar_files.mjs
Labels: patch

#63 Add XLR entries to generated package.json
  docs/javascript.md
  javascript/private/create_package_json.mjs
  javascript/private/js_pipeline.bzl
  javascript/private/package_json.bzl
  player/private/js_xlr_pipeline.bzl
Labels: patch

#73 Update JS Rules to Latest
  .circleci/config.yml
  MODULE.bazel
  examples/ts-monorepo/MODULE.bazel
  javascript/private/utils.bzl
  package.json
  player/private/config.bzl
  pnpm-lock.yaml
  yarn.lock
Labels: patch, skip-release
